### ISSUE TITLE
an aggregate blogging site

### ISSUE THREAD

**Issue by tnguyen14** [tnguyen14/tridnguyen.com#29]
My personal goal is to write more. I truly believe in the impact of writing, and I wanna be better at it.

I have lots of ideas of what to write, but not enough time. 

I know the same is true for you as well.

And when you have a tiny personal blog with a small audience (say, of 1?), it's not motivating to write often. It is sort of like a chicken and egg problem.

A possible solution? Let's band together and write. We could still write our personal blogs, with personal topics and interests, with the same authoritative and authentic voice. But let's publish them together.

It's challenging for me to have the discipline to write once a week, but if I can write once a month, that's not so bad. If we have 4 people doing this, we could have a blogging site that has new posts with a pretty good cadence, and thus appeal to readers.

Now, if we have a group of people writing together separately, we could also create a small community to bounce ideas off of, build the article together, and then publish as our own posts.

How can we make this happen? I am not sure the details yet, but here's some initial ideas:
- Each of us can still maintain our own blogs, but we pull our content together and publish in one place
- We can write about anything we want: coding, professional life, personal life and interests, etc.
- When we publish a post to this place, we can still cross-post it on our personal site (personal branding ftw!)
- If we have a spark, a seed, an idea, we could ask others to come in and work together to develop it. We can credit them for the help, but at the end of the day, the person with the idea is the owner of the article

What makes this a good idea:
- An interesting story, tidbit, insight etc. is what appeal to people. It's also how we learn to experience the world.
- Any of those becomes the chance for us to connect with others. At the end of the day, it's the connection that is important. So we write to create a community, and the goal is to grow ourselves, and grow that community, through our writing and how we adapt our writing.
- This is similar to the pastry box project, but it's not for famous people in this industry. It is for people like us, who are just starting out developers, trying to make it in this world.

**Comment by duytin90** [comment]
>I truly believe in the impact of writing

I think this is a good and important vision. Keep it along the line of writing to improve yourself and to help others maybe?

>A possible solution? Let's band together and write. We could still write our personal blogs, with personal topics and interests, with the same authoritative and authentic voice. But let's publish them together.

I think it's a good solution. 

I like the part about why it's a good idea. Solid. However, this part 
>connect with others. However, at the end of the day,

I think you might have used the "However" incorrectly. You're continuing on the same idea?

**Comment by tnguyen14** [comment]
Yeah, I could rephrase it as:

- Any of those becomes the chance for us to connect with others. At the end of the day, it's the connection that is important. So we write to create a community, and the goal is to grow ourselves, and grow that community, through our writing and how we adapt our writing.

Anyhow, I think the grammar of this issue is not too important. I just wanted to explain my motivation behind this idea.

**Comment by duytin90** [comment]
My point wasn't grammar. It actually made it more difficult to understand/ potentially imply a different meaning.

**Comment by tnguyen14** [comment]
Point taken. Updated the original post with that :)

**Comment by tnguyen14** [comment]
Other good ideas that I've learned in writing/ running my own blog:

- Github issues can be a very good (natural?) place for us developers to note down ideas, collaborate and develop them.
- WordPress is a good system to manage content, whether it's just a few posts, or a few thousand.
- Static site is a great way to make website free and fast.

I am currently drafting a blog post detailing how I am doing exactly that - brainstorming in github, drafting, editing and storing posts in WordPress and publishing them as a static site (#18). Will update once the blog post is published.

**Comment by duytin90** [comment]
To each his own. Depends on the ideas too. Maybe it works for you because you work a lot on github and are very used to it/on github a lot. If I have an idea, I usually just write an unpublished post on wordpress for it. If i need collaboration I'll publish it and others can comment on it (hasn't happened yet). I'm starting to use Any.Do to write down ideas and remind myself about it. Yes, Google Keep can do the same thing, I just don't like UI of Keep.
